---

- include_tasks: binary_deployment.yml

- name: create configuration file
  template: src=dm-worker.toml.j2 dest={{ deploy_dir }}/conf/dm-worker.toml mode=0644 backup=yes
  register: dm_worker_conf_st

- name: backup conf file
  command: mv "{{ dm_worker_conf_st.backup_file }}" "{{ backup_dir }}"
  when:
    - dm_worker_conf_st.changed
    - dm_worker_conf_st.backup_file is defined
